commit_message: '[ci skip] i18n: Translate %original_file_name% to %language%'
append_commit_message: false
files:
  - source: /translations/en_US/*.json
    translation: /translations/%locale_with_underscore%/%original_file_name%
